services:
  mysql:
    image: mysql:8.0
    container_name: zticket-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zticket
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: zticket-redis
    ports:
      - "6379:6379"

  redisinsight:
    image: redis/redisinsight:latest
    container_name: zticket-redisinsight
    ports:
      - "5540:5540"
    depends_on:
      - redis

volumes:
  mysql-data:
