spring:
  application:
    name: zticket

  datasource:
    url: jdbc:mysql://localhost:3306/zticket?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 50
      connection-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: false
    open-in-view: false

  task:
    execution:
      thread-name-prefix: "zticket-async-"
    scheduling:
      thread-name-prefix: "zticket-scheduler-"
      shutdown:
        await-termination: true
        await-termination-period: 5s

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1,expireAfterWrite=5s

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      lettuce:
        metrics: true

  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics,env,conditions,beans
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: zticket
    distribution:
      percentiles-histogram:
        http.server.requests: true
        lettuce: true

zticket:
  admission:
    interval-ms: 5000
    active-ttl-seconds: 300
    max-active-users: ${zticket.seat.total-count}
    batch-size: 100
    queue-ttl-seconds: 60
    cleanup-interval-ms: 30000
  seat:
    total-count: 1000
    hold-ttl-seconds: 300
  sync:
    interval-ms: 60000
