spring:
  application:
    name: zticket


  datasource:
    url: jdbc:mysql://localhost:3306/zticket?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      connection-timeout: 2000

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: false
    open-in-view: false

  task:
    scheduling:
      pool:
        size: 2
      thread-name-prefix: "zticket-scheduler-"
      shutdown:
        await-termination: true
        await-termination-period: 5s

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1,expireAfterWrite=2s

  data:
    redis:
      host: localhost
      port: 6379

zticket:
  admission:
    batch-size: 500
    interval-ms: 1000
    active-ttl-seconds: 300
    max-active-users: 500
  seat:
    total-count: 50
    hold-ttl-seconds: 300
  sync:
    interval-ms: 60000
