global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'zticket'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    scrape_timeout: 8s
    static_configs:
      - targets: ['app:8080']
